### ISSUE TITLE
Error 6 Overflow, aborted error on importing Artifacts

### ISSUE THREAD

**Issue by WickedShadows** [Jekoh497/RaidShadowLegend#1]
Anytime I try to import artifacts I get an Error 6 Overflow, aborted error. This happens no matter which option I choose, be it at stock level 12 or if I run it up to 16, same error. I've tried before and after importing my champs (which works without any issue).
I think this tool would be amazing for me if it would only work lol. BTW as far as timing, it pop's up rather quickly, maybe 30 seconds or less.
![Overflow aborted](https://user-images.githubusercontent.com/22035816/125172019-7c222300-e174-11eb-8afd-f574948fdd43.jpg)

**Comment by Jekoh497** [comment]
Thank you, this is solved in version 3 available for downloading 
Artefact id number need now to be long type instead of int.
Also added lastest heroes from game and associated pictures.
