### ISSUE TITLE
New version stats are WAY off

### ISSUE THREAD

**Issue by WickedShadows** [Jekoh497/RaidShadowLegend#2]
So I grabbed your new version, artifacts and champs loaded without issue now which is great however the stats are so completely far off I don't even know how to get around it. I will play around doing different things to see if I can find the issue myself and report back.
![2021-07-14_15-31-40](https://user-images.githubusercontent.com/22035816/125696148-e64bbae2-cbc4-4d4f-b820-899c54fa58a4.jpg)

**Comment by WickedShadows** [comment]
So I unhid all the sheets you have to look around a bit and right off I see in the individual champion sheet its adding an extra 0 or 2 to every imported stat.
![2021-07-14_16-25-37](https://user-images.githubusercontent.com/22035816/125700954-52b915d8-9af3-4ad7-bfa9-74aa56ca8f56.jpg)

Then if you look at where that info is coming from you see on each gear piece an extra 0 or 2 as well, so its either from the extractor adding in a multiplier it shouldn't or somehow the code pulling it in is

**Comment by Jekoh497** [comment]
I have not this issue in my own data, they are correct compared to the game view.
Can you attach or send me by mail your extracted .json file so I test and edit the json file to see where the issue can be ? thanks

**Comment by WickedShadows** [comment]
Just for the public reading this I have sent him my json and my issue file to his email so he can see what's going on on my end, in caes anyone else is having the same issues.

**Comment by Jekoh497** [comment]
ok, will apply a corrective. The issue is coming from the fact that dot (.) is the decimal separator in the json file
and in excel default decimal separator in some countries is the dot (.) and in some others countries the decimal separator is the comma (,).

**Comment by WickedShadows** [comment]
That makes a ton of sense, being in the US I have seen issues somewhat like that before but couldn't figure out how it was coming through on this one!

**Comment by Jekoh497** [comment]
I updated a version 3.1 to be suitable for both use dot or comma
now you may have right value

![image](https://user-images.githubusercontent.com/76770543/125918814-08422b9f-8b2f-4ac3-90ac-e9838a1843e3.png)

**Comment by WickedShadows** [comment]
Ok everything is working perfectly now! Great tool, Love it a lot Thank you!!!

**Comment by WickedShadows** [comment]
Now I have no idea where else to put this but I have an idea to bump this thing up a bit more. Any way you can pull in the champs level and assend? Like maybe it populates on the team screen below the champions name? So move the picture box down to right above the remove champ button. This would be GREAT to see when building a team when you have mass amounts of good champs like I do. Just a thought, not an issue

**Comment by Jekoh497** [comment]
yes that's something doable.
I was planning to add in the champions page a calculation of the damages, or debuff chance to apply per A1, A2, A3 and survivability with the actual gear and the same for the test chosen gear

**Comment by WickedShadows** [comment]
Oh wow that will be AMAZING!!!! Keep up the great work my friend!

**Comment by Jekoh497** [comment]
added stars and lvl in file 3.2 for you ;)

**Comment by WickedShadows** [comment]
Oh WOW you are the MAN!!! I will play around with this tomorrow, I'm really excited about this setup, Thank YOU!!!
